databases:
  - name: stawi-db
    plan: free
    databaseName: stawi

services:
  - type: web
    name: stawi-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEMO_DATA_ENABLED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: stawi-db
          property: connectionString
      - key: SEED
        value: "false"
      - key: PAYAZA_MODE
        sync: false
      - key: PAYAZA_PUBLIC_KEY
        sync: false
      - key: PAYAZA_SECRET_KEY
        sync: false
      - key: PAYAZA_PIN
        sync: false
      - key: PAYAZA_TENANT
        value: test
      - key: AT_ENV
        sync: false
      - key: AT_USERNAME
        sync: false
      - key: AT_API_KEY
        sync: false
      - key: AT_CALLBACK_SECRET
        generateValue: true
      - key: AT_SENDER_ID
        value: STAWI
      - key: CORS_ORIGIN
        sync: false
